In [ ]:
#Interpolação de Lagrange
import numpy as np
def lagrange(x, y, xp):
    soma = 0
    for i in range(len(y)):
        produto = 1
        print(y[i], end="")
        for j in range(len(x)):
            if j != i:
                produto = produto*(xp-x[j])/(x[i] - x[j])
                print('*( xp -', x[j], ')/(', x[i], '-', x[j], ')', end="")
        print(' + ', end="")
        soma = soma + produto*y[i]
    print()
    return soma
texto = input('digite x: ')
a = texto.split(',')
texto = input('digite y: ')
b = texto.split(',')
xp = float(input('digite xp: '))
x = np.array([float(c) for c in a])
y = np.array([float(c) for c in b])
print('f(xp): ', "%.8f" % (lagrange(x, y, xp)))

digite x: 20,25,40
digite y: 18,29,33
digite xp: 32
18.0*( xp - 25.0 )/( 20.0 - 25.0 )*( xp - 40.0 )/( 20.0 - 40.0 ) + 29.0*( xp - 20.0 )/( 25.0 - 20.0 )*( xp - 40.0 )/( 25.0 - 40.0 ) + 33.0*( xp - 20.0 )/( 40.0 - 20.0 )*( xp - 25.0 )/( 40.0 - 25.0 ) +
f(xp):  36.28000000

In [ ]:
#Interpolação de Newton
import numpy as np
def newton(x, y, xp):
    soma = m[0, 0]
    print(m[0, 0], ' + ', end="")
    for i in range(1, len(x)):
        produto = 1
        print(m[i, 0], end="")
        for j in range(i):
            produto = produto*(xp-x[j])
            print('*( xp -', x[j], ')', end="")
        print(' + ', end="")
        soma = soma + m[i, 0]*produto
    print()
    return soma
texto = input('digite x: ')
a = texto.split(',')
texto = input('digite y: ')
b = texto.split(',')
xp = float(input('digite xp: '))
x = np.array([float(c) for c in a])
y = np.array([float(c) for c in b])
m = np.zeros([len(x), len(x)])
m[0, :] = y
for i in range(1, len(x)):
  for j in range(0, len(x)-i):
    m[i, j] = (m[i-1, j+1]-m[i-1, j])/(x[i+j]-x[j])
print('Tabela de diferenças divididas: \n', m.T)
print('f(xp): ', "%.8f" % (newton(x, y, xp)))

digite x: 0,0.2,0.3,0.5
digite y: 1.008,1.064,1.125,1.343
digite xp: 0.4
Tabela de diferenças divididas:
 [[1.008 0.28  1.1   1.   ]
 [1.064 0.61  1.6   0.   ]
 [1.125 1.09  0.    0.   ]
 [1.343 0.    0.    0.   ]]
1.008  + 0.28000000000000025*( xp - 0.0 ) + 1.0999999999999976*( xp - 0.0 )*( xp - 0.2 ) + 1.000000000000007*( xp - 0.0 )*( xp - 0.2 )*( xp - 0.3 ) +
f(xp):  1.21600000

In [ ]:
#Integral trapézio simples
x0 = float(input('digite x0: '))
x1 = float(input('digite x1: '))
y0 = float(input('digite y0: '))
y1 = float(input('digite y1: '))
h = x1 - x0
I = (h/2)*(y0 + y1)
print('(', h, '/2 )*(', y0, '+', y1, ')')
print('I: ', "%.8f" % I)

digite x0: 4
digite x1: 5
digite y0: 3
digite y1: 0
( 1.0 /2 )*( 3.0 + 0.0 )
I:  1.50000000

In [ ]:
#Integral trapézio vetores
import numpy as np
texto = input('digite x: ')
x = texto.split(',')
texto = input('digite y: ')
y = texto.split(',')
x = np.array([float(c) for c in x], dtype = float)
y = np.array([float(c) for c in y], dtype = float)
soma = 0
for i in range(1, len(x)):
  h = x[i] - x[i - 1]
  I = (h/2)*(y[i] + y[i - 1])
  print('(', h, '/2 )*(', y[i], '+', y[i - 1], ') +', end="")
  soma = soma + I
print()
print('I: ', "%.8f" % soma)

digite x: 2.2,3,7.5
digite y: 5,5.1,10.7
( 0.7999999999999998 /2 )*( 5.1 + 5.0 ) +( 4.5 /2 )*( 10.7 + 5.1 ) +
I:  39.59000000

In [ ]:
#Integral trapézio composto
import numpy as np
def f(x):
  return x**2
a = float(input('digite a: '))
b = float(input('digite b: '))
n = int(input('digite n: '))
h = (b - a)/n
soma = 0
print('(', h, '/2 )*(', end="")
for i in range(n + 1):
  if i == 0 or i == n:
    soma = soma + f(a)
    print(f(a), '+', end="")
  else:
    soma = soma + 2*f(a)
    print('2*', f(a), '+', end="")
  a = a + h
print(')')
I = (h/2)*soma
print('I: ', "%.8f" % I)

digite a: 0
digite b: 1
digite n: 3
( 0.3333333333333333 /2 )*(0.0 +2* 0.1111111111111111 +2* 0.4444444444444444 +1.0 +)
I:  0.35185185

In [ ]:
#Integral primeira regra de Simpson
import numpy as np
def f(x):
  return np.exp(x)*np.cos(x)
a = float(input('digite a: '))
b = float(input('digite b: '))
h = float(input('digite h: '))
n = round((b - a)/h)
if n%2 != 0:
  n = n - 1
soma = 0
print('(', h, '/ 3 )*( ', end="")
for i in range(n + 1):
  if i == 0 or i == n:
    soma = soma + f(a)
    print(f(a), '+ ', end="")
  elif i%2 != 0:
    soma = soma + 4*f(a)
    print('4 *', f(a), '+ ', end="")
  else:
    soma = soma + 2*f(a)
    print('2 *', f(a), '+ ', end="")
  a = a + h
print(')')
I = (h/3)*soma
print('I: ', "%.8f" % I)

digite a: 0
digite b: 1.2
digite h: 0.3
( 0.3 / 3 )*( 1.0 + 4 * 1.2895693740449359 + 2 * 1.503859540558786 + 4 * 1.528913811884699 + 1.203070112722819 + )
I:  1.64847219

In [ ]:
#Integral segunda regra de Simpson
import numpy as np
def f(x):
  return np.sin(x)
a = float(input('digite a: '))
b = float(input('digite b: '))
n = int(input('digite n: '))
h = (b - a)/n
soma = 0
print('(3 *', h, '/ 8 )*( ', end="")
if n%3 != 0:
  n = n - 1
for i in range(n + 1):
  if i == 0 or i == n:
    soma = soma + f(a)
    print(f(a), '+ ', end="")
  elif i%3 == 0:
    soma = soma + 2*f(a)
    print('2 *', f(a), '+ ', end="")
  else:
    soma = soma + 3*f(a)
    print('3 *', f(a), '+ ', end="")
  a = a + h
print(')')
I = (3*h/8)*soma
print('I: ', "%.8f" % I)

digite a: 0
digite b: 1
digite n: 3
(3 * 0.3333333333333333 / 8 )*( 0.0 + 3 * 0.3271946967961522 + 3 * 0.618369803069737 + 0.8414709848078965 + )
I:  0.45977056

In [ ]:
#EDO primeira ordem com Euler
import numpy as np
def f(x, y):
  return y
t0 = float(input('digite t0: '))
y0 = float(input('digite y0: '))
h = float(input('digite h: '))
n = int(input('digite n: '))
y = y0
x = t0
print('x', 0,':', x) 
print('y', 0, ':', y)
for i in range(n):
  aux = y
  y = y + h*f(x, y)
  x = x + h
  print('x', i + 1,':', x) 
  print('y', i + 1, ':', aux, '+', h, '*', aux)
  print('y', i + 1, ':', y)
print('y: ', "%.8f" % y)

digite t0: 0
digite y0: 1
digite h: 0.25
digite n: 4
x 0 : 0.0
y 0 : 1.0
x 1 : 0.25
y 1 : 1.0 + 0.25 * 1.0
y 1 : 1.25
x 2 : 0.5
y 2 : 1.25 + 0.25 * 1.25
y 2 : 1.5625
x 3 : 0.75
y 3 : 1.5625 + 0.25 * 1.5625
y 3 : 1.953125
x 4 : 1.0
y 4 : 1.953125 + 0.25 * 1.953125
y 4 : 2.44140625
y:  2.44140625

In [ ]:
#EDO primeira ordem com Euler modificado (Heun)
import numpy as np
def f(x, y):
  return y
t0 = float(input('digite t0: '))
y0 = float(input('digite y0: '))
h = float(input('digite h: '))
n = int(input('digite n: '))
y = y0
x = t0
print('x', 0,':', x) 
print('y', 0, ':', y)
for i in range(n):
  aux = y
  k1 = f(x, y)
  print('k1:', k1)
  k2 = f(x + h, y + h*k1)
  print('k2:', k2)
  y = y + (h/2)*(k1 + k2)
  x = x + h
  print('x', i + 1,':', x) 
  print('y', i + 1, ':', aux, '+ (', h, '/2 )*(', k1, '+', k2, ')')
  print('y', i + 1, ':', y)
print('y: ', "%.8f" % y)

digite t0: 0
digite y0: 1
digite h: 0.25
digite n: 4
x 0 : 0.0
y 0 : 1.0
k1: 1.0
k2: 1.25
x 1 : 0.25
y 1 : 1.0 + ( 0.25 /2 )*( 1.0 + 1.25 )
y 1 : 1.28125
k1: 1.28125
k2: 1.6015625
x 2 : 0.5
y 2 : 1.28125 + ( 0.25 /2 )*( 1.28125 + 1.6015625 )
y 2 : 1.6416015625
k1: 1.6416015625
k2: 2.052001953125
x 3 : 0.75
y 3 : 1.6416015625 + ( 0.25 /2 )*( 1.6416015625 + 2.052001953125 )
y 3 : 2.103302001953125
k1: 2.103302001953125
k2: 2.6291275024414062
x 4 : 1.0
y 4 : 2.103302001953125 + ( 0.25 /2 )*( 2.103302001953125 + 2.6291275024414062 )
y 4 : 2.6948556900024414
y:  2.69485569

In [ ]:
#Sistema de EDO de primeira ordem com Ponto Médio
import numpy as np
def f(x, y):
  return y
t0 = float(input())
y0 = float(input())
h = float(input())
n = int(input())
y = y0
x = t0
print('x', 0,':', x) 
print('y', 0, ':', y)
for i in range(n):
  aux = y
  k1 = f(x, y) 
  print('k1:', k1)
  k2 = f(x + h/2, y + (h/2)*k1)
  print('k2:', k2)
  y = y + h*k2
  x = x + h
  print('x', i + 1,':', x) 
  print('y', i + 1, ':', aux, '+ (', h, '/2 )*(', k1, '+', k2, ')')
  print('y', i + 1, ':', y)
print("%.8f" % y)

0
1
0.25
4
x 0 : 0.0
y 0 : 1.0
k1: 1.0
k2: 1.125
x 1 : 0.25
y 1 : 1.0 + ( 0.25 /2 )*( 1.0 + 1.125 )
y 1 : 1.28125
k1: 1.28125
k2: 1.44140625
x 2 : 0.5
y 2 : 1.28125 + ( 0.25 /2 )*( 1.28125 + 1.44140625 )
y 2 : 1.6416015625
k1: 1.6416015625
k2: 1.8468017578125
x 3 : 0.75
y 3 : 1.6416015625 + ( 0.25 /2 )*( 1.6416015625 + 1.8468017578125 )
y 3 : 2.103302001953125
k1: 2.103302001953125
k2: 2.3662147521972656
x 4 : 1.0
y 4 : 2.103302001953125 + ( 0.25 /2 )*( 2.103302001953125 + 2.3662147521972656 )
y 4 : 2.6948556900024414
2.69485569

In [ ]:
#EDO segunda ordem com RK4
import numpy as np
def f1(t, y, z):
  zponto = -9.81
  return zponto
def f2(t, y, z):
  yponto = z
  return yponto
t0 = 0
y0 = float(input('digite y0: '))
z0 = 0
h = 1
t = t0
y = y0
z = z0
while y > 0:
  aux = y
  k1y = f2(t, y, z) 
  print('k1y:', k1y)
  k1z = f1(t, y, z)
  print('k1z:', k1z)
  k2y = f2(t + h, y + h*k1y, z + h*k1z)
  print('k2y:', k2y)
  k2z = f1(t + h, y + h*k1y, z + h*k1z)
  print('k2z:', k2z)
  y = y + (h/2)*(k1y + k2y)
  z = z + (h/2)*(k1z + k2z)
  t = t + h
  print('t', i + 1,':', t) 
  print('y', i + 1, ':', aux, '+ (', h, '/2 )*(', k1, '+', k2, ')')
  print('y', i + 1, ':', y)
print('t:', "%.8f" % t)

digite y0: 32000
k1y: 0
k1z: -9.81
k2y: -9.81
k2z: -9.81
t 4 : 1
y 4 : 32000.0 + ( 1 /2 )*( 2.103302001953125 + 2.3662147521972656 )
y 4 : 31995.095
k1y: -9.81
k1z: -9.81
k2y: -19.62
k2z: -9.81
t 4 : 2
y 4 : 31995.095 + ( 1 /2 )*( 2.103302001953125 + 2.3662147521972656 )
y 4 : 31980.38
k1y: -19.62
k1z: -9.81
k2y: -29.43
k2z: -9.81
t 4 : 3
y 4 : 31980.38 + ( 1 /2 )*( 2.103302001953125 + 2.3662147521972656 )
y 4 : 31955.855
k1y: -29.43
k1z: -9.81
k2y: -39.24
k2z: -9.81
t 4 : 4
y 4 : 31955.855 + ( 1 /2 )*( 2.103302001953125 + 2.3662147521972656 )
y 4 : 31921.52
k1y: -39.24
k1z: -9.81
k2y: -49.050000000000004
k2z: -9.81
t 4 : 5
y 4 : 31921.52 + ( 1 /2 )*( 2.103302001953125 + 2.3662147521972656 )
y 4 : 31877.375
k1y: -49.050000000000004
k1z: -9.81
k2y: -58.86000000000001
k2z: -9.81
t 4 : 6
y 4 : 31877.375 + ( 1 /2 )*( 2.103302001953125 + 2.3662147521972656 )
y 4 : 31823.42
k1y: -58.86000000000001
k1z: -9.81
k2y: -68.67
k2z: -9.81
t 4 : 7
y 4 : 31823.42 + ( 1 /2 )*( 2.103302001953125 + 2.3662147521972656 )
y 4 : 31759.655
k1y: -68.67
k1z: -9.81
k2y: -78.48
k2z: -9.81
t 4 : 8
y 4 : 31759.655 + ( 1 /2 )*( 2.103302001953125 + 2.3662147521972656 )
y 4 : 31686.079999999998
k1y: -78.48
k1z: -9.81
k2y: -88.29
k2z: -9.81
t 4 : 9
y 4 : 31686.079999999998 + ( 1 /2 )*( 2.103302001953125 + 2.3662147521972656 )
y 4 : 31602.695
k1y: -88.29
k1z: -9.81
k2y: -98.10000000000001
k2z: -9.81
t 4 : 10
y 4 : 31602.695 + ( 1 /2 )*( 2.103302001953125 + 2.3662147521972656 )
y 4 : 31509.5
k1y: -98.10000000000001
k1z: -9.81
k2y: -107.91000000000001
k2z: -9.81
t 4 : 11
y 4 : 31509.5 + ( 1 /2 )*( 2.103302001953125 + 2.3662147521972656 )
y 4 : 31406.495
k1y: -107.91000000000001
k1z: -9.81
k2y: -117.72000000000001
k2z: -9.81
t 4 : 12
y 4 : 31406.495 + ( 1 /2 )*( 2.103302001953125 + 2.3662147521972656 )
y 4 : 31293.68
k1y: -117.72000000000001
k1z: -9.81
k2y: -127.53000000000002
k2z: -9.81
t 4 : 13
y 4 : 31293.68 + ( 1 /2 )*( 2.103302001953125 + 2.3662147521972656 )
y 4 : 31171.055
k1y: -127.53000000000002
k1z: -9.81
k2y: -137.34
k2z: -9.81
t 4 : 14
y 4 : 31171.055 + ( 1 /2 )*( 2.103302001953125 + 2.3662147521972656 )
y 4 : 31038.62
k1y: -137.34
k1z: -9.81
k2y: -147.15
k2z: -9.81
t 4 : 15
y 4 : 31038.62 + ( 1 /2 )*( 2.103302001953125 + 2.3662147521972656 )
y 4 : 30896.375
k1y: -147.15
k1z: -9.81
k2y: -156.96
k2z: -9.81
t 4 : 16
y 4 : 30896.375 + ( 1 /2 )*( 2.103302001953125 + 2.3662147521972656 )
y 4 : 30744.32
k1y: -156.96
k1z: -9.81
k2y: -166.77
k2z: -9.81
t 4 : 17
y 4 : 30744.32 + ( 1 /2 )*( 2.103302001953125 + 2.3662147521972656 )
y 4 : 30582.454999999998
k1y: -166.77
k1z: -9.81
k2y: -176.58
k2z: -9.81
t 4 : 18
y 4 : 30582.454999999998 + ( 1 /2 )*( 2.103302001953125 + 2.3662147521972656 )
y 4 : 30410.78
k1y: -176.58
k1z: -9.81
k2y: -186.39000000000001
k2z: -9.81
t 4 : 19
y 4 : 30410.78 + ( 1 /2 )*( 2.103302001953125 + 2.3662147521972656 )
y 4 : 30229.295
k1y: -186.39000000000001
k1z: -9.81
k2y: -196.20000000000002
k2z: -9.81
t 4 : 20
y 4 : 30229.295 + ( 1 /2 )*( 2.103302001953125 + 2.3662147521972656 )
y 4 : 30038.0
k1y: -196.20000000000002
k1z: -9.81
k2y: -206.01000000000002
k2z: -9.81
t 4 : 21
y 4 : 30038.0 + ( 1 /2 )*( 2.103302001953125 + 2.3662147521972656 )
y 4 : 29836.895
k1y: -206.01000000000002
k1z: -9.81
k2y: -215.82000000000002
k2z: -9.81
t 4 : 22
y 4 : 29836.895 + ( 1 /2 )*( 2.103302001953125 + 2.3662147521972656 )
y 4 : 29625.98
k1y: -215.82000000000002
k1z: -9.81
k2y: -225.63000000000002
k2z: -9.81
t 4 : 23
y 4 : 29625.98 + ( 1 /2 )*( 2.103302001953125 + 2.3662147521972656 )
y 4 : 29405.255
k1y: -225.63000000000002
k1z: -9.81
k2y: -235.44000000000003
k2z: -9.81
t 4 : 24
y 4 : 29405.255 + ( 1 /2 )*( 2.103302001953125 + 2.3662147521972656 )
y 4 : 29174.72
k1y: -235.44000000000003
k1z: -9.81
k2y: -245.25000000000003
k2z: -9.81
t 4 : 25
y 4 : 29174.72 + ( 1 /2 )*( 2.103302001953125 + 2.3662147521972656 )
y 4 : 28934.375
k1y: -245.25000000000003
k1z: -9.81
k2y: -255.06000000000003
k2z: -9.81
t 4 : 26
y 4 : 28934.375 + ( 1 /2 )*( 2.103302001953125 + 2.3662147521972656 )
y 4 : 28684.22
k1y: -255.06000000000003
k1z: -9.81
k2y: -264.87
k2z: -9.81
t 4 : 27
y 4 : 28684.22 + ( 1 /2 )*( 2.103302001953125 + 2.3662147521972656 )
y 4 : 28424.255
k1y: -264.87
k1z: -9.81
k2y: -274.68
k2z: -9.81
t 4 : 28
y 4 : 28424.255 + ( 1 /2 )*( 2.103302001953125 + 2.3662147521972656 )
y 4 : 28154.48
k1y: -274.68
k1z: -9.81
k2y: -284.49
k2z: -9.81
t 4 : 29
y 4 : 28154.48 + ( 1 /2 )*( 2.103302001953125 + 2.3662147521972656 )
y 4 : 27874.895
k1y: -284.49
k1z: -9.81
k2y: -294.3
k2z: -9.81
t 4 : 30
y 4 : 27874.895 + ( 1 /2 )*( 2.103302001953125 + 2.3662147521972656 )
y 4 : 27585.5
k1y: -294.3
k1z: -9.81
k2y: -304.11
k2z: -9.81
t 4 : 31
y 4 : 27585.5 + ( 1 /2 )*( 2.103302001953125 + 2.3662147521972656 )
y 4 : 27286.295
k1y: -304.11
k1z: -9.81
k2y: -313.92
k2z: -9.81
t 4 : 32
y 4 : 27286.295 + ( 1 /2 )*( 2.103302001953125 + 2.3662147521972656 )
y 4 : 26977.28
k1y: -313.92
k1z: -9.81
k2y: -323.73
k2z: -9.81
t 4 : 33
y 4 : 26977.28 + ( 1 /2 )*( 2.103302001953125 + 2.3662147521972656 )
y 4 : 26658.454999999998
k1y: -323.73
k1z: -9.81
k2y: -333.54
k2z: -9.81
t 4 : 34
y 4 : 26658.454999999998 + ( 1 /2 )*( 2.103302001953125 + 2.3662147521972656 )
y 4 : 26329.82
k1y: -333.54
k1z: -9.81
k2y: -343.35
k2z: -9.81
t 4 : 35
y 4 : 26329.82 + ( 1 /2 )*( 2.103302001953125 + 2.3662147521972656 )
y 4 : 25991.375
k1y: -343.35
k1z: -9.81
k2y: -353.16
k2z: -9.81
t 4 : 36
y 4 : 25991.375 + ( 1 /2 )*( 2.103302001953125 + 2.3662147521972656 )
y 4 : 25643.12
k1y: -353.16
k1z: -9.81
k2y: -362.97
k2z: -9.81
t 4 : 37
y 4 : 25643.12 + ( 1 /2 )*( 2.103302001953125 + 2.3662147521972656 )
y 4 : 25285.055
k1y: -362.97
k1z: -9.81
k2y: -372.78000000000003
k2z: -9.81
t 4 : 38
y 4 : 25285.055 + ( 1 /2 )*( 2.103302001953125 + 2.3662147521972656 )
y 4 : 24917.18
k1y: -372.78000000000003
k1z: -9.81
k2y: -382.59000000000003
k2z: -9.81
t 4 : 39
y 4 : 24917.18 + ( 1 /2 )*( 2.103302001953125 + 2.3662147521972656 )
y 4 : 24539.495
k1y: -382.59000000000003
k1z: -9.81
k2y: -392.40000000000003
k2z: -9.81
t 4 : 40
y 4 : 24539.495 + ( 1 /2 )*( 2.103302001953125 + 2.3662147521972656 )
y 4 : 24152.0
k1y: -392.40000000000003
k1z: -9.81
k2y: -402.21000000000004
k2z: -9.81
t 4 : 41
y 4 : 24152.0 + ( 1 /2 )*( 2.103302001953125 + 2.3662147521972656 )
y 4 : 23754.695
k1y: -402.21000000000004
k1z: -9.81
k2y: -412.02000000000004
k2z: -9.81
t 4 : 42
y 4 : 23754.695 + ( 1 /2 )*( 2.103302001953125 + 2.3662147521972656 )
y 4 : 23347.579999999998
k1y: -412.02000000000004
k1z: -9.81
k2y: -421.83000000000004
k2z: -9.81
t 4 : 43
y 4 : 23347.579999999998 + ( 1 /2 )*( 2.103302001953125 + 2.3662147521972656 )
y 4 : 22930.655
k1y: -421.83000000000004
k1z: -9.81
k2y: -431.64000000000004
k2z: -9.81
t 4 : 44
y 4 : 22930.655 + ( 1 /2 )*( 2.103302001953125 + 2.3662147521972656 )
y 4 : 22503.92
k1y: -431.64000000000004
k1z: -9.81
k2y: -441.45000000000005
k2z: -9.81
t 4 : 45
y 4 : 22503.92 + ( 1 /2 )*( 2.103302001953125 + 2.3662147521972656 )
y 4 : 22067.375
k1y: -441.45000000000005
k1z: -9.81
k2y: -451.26000000000005
k2z: -9.81
t 4 : 46
y 4 : 22067.375 + ( 1 /2 )*( 2.103302001953125 + 2.3662147521972656 )
y 4 : 21621.02
k1y: -451.26000000000005
k1z: -9.81
k2y: -461.07000000000005
k2z: -9.81
t 4 : 47
y 4 : 21621.02 + ( 1 /2 )*( 2.103302001953125 + 2.3662147521972656 )
y 4 : 21164.855
k1y: -461.07000000000005
k1z: -9.81
k2y: -470.88000000000005
k2z: -9.81
t 4 : 48
y 4 : 21164.855 + ( 1 /2 )*( 2.103302001953125 + 2.3662147521972656 )
y 4 : 20698.88
k1y: -470.88000000000005
k1z: -9.81
k2y: -480.69000000000005
k2z: -9.81
t 4 : 49
y 4 : 20698.88 + ( 1 /2 )*( 2.103302001953125 + 2.3662147521972656 )
y 4 : 20223.095
k1y: -480.69000000000005
k1z: -9.81
k2y: -490.50000000000006
k2z: -9.81
t 4 : 50
y 4 : 20223.095 + ( 1 /2 )*( 2.103302001953125 + 2.3662147521972656 )
y 4 : 19737.5
k1y: -490.50000000000006
k1z: -9.81
k2y: -500.31000000000006
k2z: -9.81
t 4 : 51
y 4 : 19737.5 + ( 1 /2 )*( 2.103302001953125 + 2.3662147521972656 )
y 4 : 19242.095
k1y: -500.31000000000006
k1z: -9.81
k2y: -510.12000000000006
k2z: -9.81
t 4 : 52
y 4 : 19242.095 + ( 1 /2 )*( 2.103302001953125 + 2.3662147521972656 )
y 4 : 18736.88
k1y: -510.12000000000006
k1z: -9.81
k2y: -519.9300000000001
k2z: -9.81
t 4 : 53
y 4 : 18736.88 + ( 1 /2 )*( 2.103302001953125 + 2.3662147521972656 )
y 4 : 18221.855
k1y: -519.9300000000001
k1z: -9.81
k2y: -529.74
k2z: -9.81
t 4 : 54
y 4 : 18221.855 + ( 1 /2 )*( 2.103302001953125 + 2.3662147521972656 )
y 4 : 17697.02
k1y: -529.74
k1z: -9.81
k2y: -539.55
k2z: -9.81
t 4 : 55
y 4 : 17697.02 + ( 1 /2 )*( 2.103302001953125 + 2.3662147521972656 )
y 4 : 17162.375
k1y: -539.55
k1z: -9.81
k2y: -549.3599999999999
k2z: -9.81
t 4 : 56
y 4 : 17162.375 + ( 1 /2 )*( 2.103302001953125 + 2.3662147521972656 )
y 4 : 16617.92
k1y: -549.3599999999999
k1z: -9.81
k2y: -559.1699999999998
k2z: -9.81
t 4 : 57
y 4 : 16617.92 + ( 1 /2 )*( 2.103302001953125 + 2.3662147521972656 )
y 4 : 16063.654999999999
k1y: -559.1699999999998
k1z: -9.81
k2y: -568.9799999999998
k2z: -9.81
t 4 : 58
y 4 : 16063.654999999999 + ( 1 /2 )*( 2.103302001953125 + 2.3662147521972656 )
y 4 : 15499.579999999998
k1y: -568.9799999999998
k1z: -9.81
k2y: -578.7899999999997
k2z: -9.81
t 4 : 59
y 4 : 15499.579999999998 + ( 1 /2 )*( 2.103302001953125 + 2.3662147521972656 )
y 4 : 14925.694999999998
k1y: -578.7899999999997
k1z: -9.81
k2y: -588.5999999999997
k2z: -9.81
t 4 : 60
y 4 : 14925.694999999998 + ( 1 /2 )*( 2.103302001953125 + 2.3662147521972656 )
y 4 : 14341.999999999998
k1y: -588.5999999999997
k1z: -9.81
k2y: -598.4099999999996
k2z: -9.81
t 4 : 61
y 4 : 14341.999999999998 + ( 1 /2 )*( 2.103302001953125 + 2.3662147521972656 )
y 4 : 13748.494999999999
k1y: -598.4099999999996
k1z: -9.81
k2y: -608.2199999999996
k2z: -9.81
t 4 : 62
y 4 : 13748.494999999999 + ( 1 /2 )*( 2.103302001953125 + 2.3662147521972656 )
y 4 : 13145.18
k1y: -608.2199999999996
k1z: -9.81
k2y: -618.0299999999995
k2z: -9.81
t 4 : 63
y 4 : 13145.18 + ( 1 /2 )*( 2.103302001953125 + 2.3662147521972656 )
y 4 : 12532.055
k1y: -618.0299999999995
k1z: -9.81
k2y: -627.8399999999995
k2z: -9.81
t 4 : 64
y 4 : 12532.055 + ( 1 /2 )*( 2.103302001953125 + 2.3662147521972656 )
y 4 : 11909.12
k1y: -627.8399999999995
k1z: -9.81
k2y: -637.6499999999994
k2z: -9.81
t 4 : 65
y 4 : 11909.12 + ( 1 /2 )*( 2.103302001953125 + 2.3662147521972656 )
y 4 : 11276.375000000002
k1y: -637.6499999999994
k1z: -9.81
k2y: -647.4599999999994
k2z: -9.81
t 4 : 66
y 4 : 11276.375000000002 + ( 1 /2 )*( 2.103302001953125 + 2.3662147521972656 )
y 4 : 10633.820000000003
k1y: -647.4599999999994
k1z: -9.81
k2y: -657.2699999999993
k2z: -9.81
t 4 : 67
y 4 : 10633.820000000003 + ( 1 /2 )*( 2.103302001953125 + 2.3662147521972656 )
y 4 : 9981.455000000004
k1y: -657.2699999999993
k1z: -9.81
k2y: -667.0799999999992
k2z: -9.81
t 4 : 68
y 4 : 9981.455000000004 + ( 1 /2 )*( 2.103302001953125 + 2.3662147521972656 )
y 4 : 9319.280000000004
k1y: -667.0799999999992
k1z: -9.81
k2y: -676.8899999999992
k2z: -9.81
t 4 : 69
y 4 : 9319.280000000004 + ( 1 /2 )*( 2.103302001953125 + 2.3662147521972656 )
y 4 : 8647.295000000006
k1y: -676.8899999999992
k1z: -9.81
k2y: -686.6999999999991
k2z: -9.81
t 4 : 70
y 4 : 8647.295000000006 + ( 1 /2 )*( 2.103302001953125 + 2.3662147521972656 )
y 4 : 7965.500000000006
k1y: -686.6999999999991
k1z: -9.81
k2y: -696.5099999999991
k2z: -9.81
t 4 : 71
y 4 : 7965.500000000006 + ( 1 /2 )*( 2.103302001953125 + 2.3662147521972656 )
y 4 : 7273.895000000008
k1y: -696.5099999999991
k1z: -9.81
k2y: -706.319999999999
k2z: -9.81
t 4 : 72
y 4 : 7273.895000000008 + ( 1 /2 )*( 2.103302001953125 + 2.3662147521972656 )
y 4 : 6572.480000000009
k1y: -706.319999999999
k1z: -9.81
k2y: -716.129999999999
k2z: -9.81
t 4 : 73
y 4 : 6572.480000000009 + ( 1 /2 )*( 2.103302001953125 + 2.3662147521972656 )
y 4 : 5861.25500000001
k1y: -716.129999999999
k1z: -9.81
k2y: -725.9399999999989
k2z: -9.81
t 4 : 74
y 4 : 5861.25500000001 + ( 1 /2 )*( 2.103302001953125 + 2.3662147521972656 )
y 4 : 5140.220000000011
k1y: -725.9399999999989
k1z: -9.81
k2y: -735.7499999999989
k2z: -9.81
t 4 : 75
y 4 : 5140.220000000011 + ( 1 /2 )*( 2.103302001953125 + 2.3662147521972656 )
y 4 : 4409.375000000013
k1y: -735.7499999999989
k1z: -9.81
k2y: -745.5599999999988
k2z: -9.81
t 4 : 76
y 4 : 4409.375000000013 + ( 1 /2 )*( 2.103302001953125 + 2.3662147521972656 )
y 4 : 3668.720000000014
k1y: -745.5599999999988
k1z: -9.81
k2y: -755.3699999999988
k2z: -9.81
t 4 : 77
y 4 : 3668.720000000014 + ( 1 /2 )*( 2.103302001953125 + 2.3662147521972656 )
y 4 : 2918.255000000015
k1y: -755.3699999999988
k1z: -9.81
k2y: -765.1799999999987
k2z: -9.81
t 4 : 78
y 4 : 2918.255000000015 + ( 1 /2 )*( 2.103302001953125 + 2.3662147521972656 )
y 4 : 2157.9800000000164
k1y: -765.1799999999987
k1z: -9.81
k2y: -774.9899999999986
k2z: -9.81
t 4 : 79
y 4 : 2157.9800000000164 + ( 1 /2 )*( 2.103302001953125 + 2.3662147521972656 )
y 4 : 1387.8950000000177
k1y: -774.9899999999986
k1z: -9.81
k2y: -784.7999999999986
k2z: -9.81
t 4 : 80
y 4 : 1387.8950000000177 + ( 1 /2 )*( 2.103302001953125 + 2.3662147521972656 )
y 4 : 608.0000000000191
k1y: -784.7999999999986
k1z: -9.81
k2y: -794.6099999999985
k2z: -9.81
t 4 : 81
y 4 : 608.0000000000191 + ( 1 /2 )*( 2.103302001953125 + 2.3662147521972656 )
y 4 : -181.70499999997946
t: 81.00000000

In [ ]:
#EDO primeira ordem com Euler
import numpy as np
def f(s, i, r, n):
  return -0.06*i*s/n
def f1(s, i, r, n):
  return 0.06*i*s/n - 0.02*i
def f2(s, i, r, n):
  return 0.02*i
s0 = 206.7
i0 = 1.3
r0 = 13
n0 = 221
t0 = 0
h = 50
s = s0
i = i0
r = r0
n = n0
t = t0
print('s', 0,':', s) 
print('i', 0, ':', i)
while t < 200:
  aux = s
  aux1 = i
  s = s + h*f(s, i, r, n)
  i = i + h*f1(s, i, r, n)
  r = r + h*f2(s, i, r, n)
  print('t',':', t) 
  print('s', ':', aux, '+', h, '*', aux)
  print('s', ':', s)
  print('i', ':', aux1, '+', h, '*', aux1)
  print('i', ':', i)
  t = t + h

s 0 : 206.7
i 0 : 1.3
t : 0
s : 206.7 + 50 * 206.7
s : 203.05235294117645
i : 1.3 + 50 * 1.3
i : 3.583276816608996
t : 50
s : 203.05235294117645 + 50 * 203.05235294117645
s : 193.1755277531399
i : 3.583276816608996 + 50 * 3.583276816608996
i : 9.396398961095482
t : 100
s : 193.1755277531399 + 50 * 193.1755277531399
s : 168.53542374922125
i : 9.396398961095482 + 50 * 9.396398961095482
i : 21.497186614818588
t : 150
s : 168.53542374922125 + 50 * 168.53542374922125
s : 119.35391982780219
i : 21.497186614818588 + 50 * 21.497186614818588
i : 34.82950435857502